#equivilents for player colored gui elements
#in other cfgs just reference the first entry, followed by red (used as first entry but could be swapped) blue, green, yellow, white, neutral
# can also use custom sprites eg.
# [ 93,"CTA_RED_64","CTA_BLUE_64","CTA_GREEN_64","CTA_YELLOW_64"],#cta_high

#stuff in gui2-xx.dat
gui_panel_sprites = [
    [116,116,558,560,564,562,  0],#cta_low
    [ 93, 93,574,576,580,578,  0],#cta_high
    [ 83, 83,601,603,607,605,669],#grdpost_low
    [ 55, 55,609,611,615,613,671],#grdpost_high
    [468,468,649,650,652,651,677],#creatr_mood_vhappy
    [469,469,641,642,644,643,675],#creatr_mood_happy
    [470,470,637,638,640,639,674],#creatr_mood_content
    [471,471,633,634,636,635,673],#creatr_mood_angry
    [472,472,645,646,648,647,676],#creatr_mood_livid
    [108,108,566,568,572,570,  0],#sight_low
    [ 85, 85,582,584,588,586,  0],#sight_high
    [ 15, 15,617,619,623,621,  0],#rpanel_tab_crtra
    [ 16, 16,618,620,624,622,  0],#rpanel_tab_crtrd
    [  9,  9,625,627,631,629,  0],#rpanel_tab_rooma
    [ 10, 10,626,628,632,630,  0],#rpanel_tab_roomd
    [154,154,653,655,659,657,  0],#trap_alarm_low
    [132,132,661,663,667,665,  0],#trap_alarm_high
    [323,323,325,327,329,533,468],#plyrsym_symbol_player
    [535,535,536,537,538,539,541],#plyrsym_symbol_player_dead
    [324,324,326,328,330,542,  0],#plyrsym_symbol_room
    [488,488,489,490,491,533,468],#plyrsym_symbol_player_ally
]

#stuff in pointerxx.dat
pointer_sprites = [
    [ 40, 40,203,211,227,219,  0],#quadptr_power_cta
    [193,193,267,243,270,269,  0],#tileptr_power_cta
    [ 80, 80,235,268,259,251,  0],#quadptr_power_mkdigger
    [ 38, 38,271,272,274,273,  0],#tileptr_room_guardpst
    [  9,  9,275,276,278,277,  0],#tileptr_trap_alarm
]

#stuff in gui1-xx.dat
button_sprite = [
    [ 62, 62,127,128,129,130,  0],#creatr_state_cta
]


#stuff in creatures.jty
#only works for cta flag
animationIds = [
    [ 867, 867,873,879,885,"CTA_WHITE_ACTIVATE",  0,"CTA_PURPLE_ACTIVATE",  "CTA_BLACK_ACTIVATE",  "CTA_ORANGE_ACTIVATE"  ],#cta_birth_anim_idx
    [ 868, 868,874,880,886,"CTA_WHITE_ACTIVE",    0,"CTA_PURPLE_ACTIVE",    "CTA_BLACK_ACTIVE",    "CTA_ORANGE_ACTIVE"    ],#cta_alive_anim_idx
    [ 869, 869,875,881,887,"CTA_WHITE_DEACTIVATE",0,"CTA_PURPLE_DEACTIVATE","CTA_BLACK_DEACTIVATE","CTA_ORANGE_DEACTIVATE"],#cta_leave_anim_idx
]
