name: Alpha Patches

on:
  workflow_call:
  workflow_dispatch:

jobs:
  build-alpha-patch:

    name: "Build Alpha Patch"
    runs-on: ubuntu-24.04

    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
        
    - uses: Trass3r/setup-cpp@master

    - name: Update system
      run: |
        set -eux
        sudo apt update
        sudo apt install -y build-essential g++-mingw-w64-i686 libpng16-16t64

    - name: Build gfx
      run: |
        set -eux
        BUILD_NUMBER=$(git rev-list --count HEAD)
        PACKAGE_SUFFIX=Alpha
        make BUILD_NUMBER=$BUILD_NUMBER PACKAGE_SUFFIX=$PACKAGE_SUFFIX pkg-enginegfx

    - name: Build
      run: |
        set -eux
        BUILD_NUMBER=$(git rev-list --count HEAD)
        PACKAGE_SUFFIX=Alpha
        make BUILD_NUMBER=$BUILD_NUMBER PACKAGE_SUFFIX=$PACKAGE_SUFFIX heavylog DEBUG=1 -k
        make BUILD_NUMBER=$BUILD_NUMBER PACKAGE_SUFFIX=$PACKAGE_SUFFIX standard
        make BUILD_NUMBER=$BUILD_NUMBER PACKAGE_SUFFIX=$PACKAGE_SUFFIX package
        echo "ZIP_NAME=$(basename -s .7z pkg/keeperfx*.7z)" >> $GITHUB_ENV
        rm pkg/keeperfx*.7z

    - name: Upload artifact
      id: upload-artifact
      uses: actions/upload-artifact@v4
      with:
        name: ${{ env.ZIP_NAME }}
        path: pkg/**